ECCC-MSC/msc-animet

- src/components/GeoMetTree.vue
- src/components/MapViewer.vue
- src/components/PermaLink.vue
- src/locales/en/common.json
- src/locales/fr/common.json
- src/store/modules/Layers.js
- src/views/Home.vue
Added a new tab called special layers with the possibility of adding overlays of major cities from geogratis and geopolitical boundaries from toporama.
> Added geopolitical boundaries and major cities overlays

- src/locales/en/common.json
- src/locales/fr/common.json
- src/store/modules/Layers.js
Fixed small wording issues and changed order of overlays.
> Changed wording and overlays order

- src/components/AppBar.vue
- src/components/MapTimeControls.vue
- src/components/MapViewer.vue
Added orange marker as well as changed how the dates were displayed to show current time on the range slider.
Changed styling of the extent markers.
Also removed unused piece of code.
> Animet enhancement 283 pt

- src/components/Layers/SnappedLayerHandler.vue
- src/components/Time/TimeControls.vue
- src/locales/en/common.json
- src/locales/fr/common.json
- Added tooltip in french and english for non-temporal clock icon;
- Removed some code that was commented that I forgot to remove.
> Added tooltip for non temporal and removed commented code

- src/components/Map/MapControls.vue
- src/components/Share/PermaLink.vue
- src/locales/en/common.json
- src/locales/fr/common.json
- src/store/modules/Layers.js
- src/views/Home.vue
New button in the menu to color the map. Button makes it possible to hide/show the basemap. Also works with permalink where `&color=none` will set the basemap invisible.
> Added possibility to make the basemap invisible

- src/components/Animation/CreateAnimation.vue
- src/components/Layers/ModelRunHandler.vue
- src/components/Map/LegendSelector.vue
- src/components/Map/MapControls.vue
- src/components/Time/TimeControls.vue
v-container doesn't seem to be able to see changes that happen to the theme unlike all other components used, as such I needed to bind the style property for both occurrences of the v-container.
> Fixed v-container not changing according to the color theme

- src/components/Layers/LayerTree.vue
- src/components/Map/MapCanvas.vue
Fixed overlay dark-theme text
Fixed invisible map background to be white in black theme
> Fixed small black theme problems

- README.md
`Adding custom WMS sources` section in the README has been added.
> Added how to add custom WMS sources to AniMet in the README

- src/components/Map/GetFeatureInfo.vue
Popup will close whenever:
- a layer is added or removed;
- current time changes;
- model run changes for any layer;
- slider, arrows or play button event happens;
- any other time event, even it it does not change the current time;
- Will not be removed if layers are simply made invisible.
> Popup now closes when any time related event occurs

- CONTRIBUTING.md
- SECURITY.md
This PR adds the initial `CONTRIBUTING.MD` and `SECURITY.md` documents to assist those wishing to contribute to the project or report security issues.
> add CONTRIBUTING.md and SECURITY.md docs

- src/App.vue
- src/components/GlobalConfigs/LanguageSelect.vue
Language selection has been added to the list of local storage items with Locale and Theme.
> Language now remembered

- src/components/Map/LegendControls.vue
- src/components/Map/MapCanvas.vue
- src/components/Map/SidePanel.vue
- src/store/modules/Layers.js
- src/views/Home.vue
Added info to hide the scale line, the openstreetmap contributors and the animet version in the bottom.
Also repositioned legend after topMenus and title are removed.
Fixed a bug with waitForElements function.
> Fixed some positioning after hiding and added info

- src/components/GlobalConfigs/MapCustomization.vue
- src/locales/en/common.json
- src/locales/fr/common.json
Minor changes for the tooltip and changed the icon so it's not confused with download/upload
> Change basemap to map and removed arrow for consistency

- src/components/Layers/StyleHandler.vue
- Palette icon for styles selection changes to outline when the legend isn't being displayed;
- Added primary color and checkmark icon to show which style is currently selected among the list.
> Made it clearer which legends are displayed

- src/components/Map/LegendControls.vue
- src/components/Map/MapCanvas.vue
An index is now kept in memory of which legend was last selected and if you press the del button on your keyboard, that legend will be removed.
> Click on legend and press delete to remove legend

- src/components/Animation/ExportAnimation.vue
Small MR to not remove dashes from titles in the resulting output filename.
> Dashes kept in the output filename

- src/components/Animation/CreateAnimation.vue
- src/components/Time/AnimationControls/PlayPauseControls.vue
- Added a lock for the play event just in case;
- Fixed animation blocking when the playHead was on the first thumb of the extent when beginning the animation on new ol version.
> Fixed issues with animation and ol v9 and added lock

- src/components/Map/MapCanvas.vue
- Progress bar has been moved outside of the map div which fixes the memory leak issue with the IntersectionObserver. This observer checks intersections with its parent so it seemed to have some weird interactions when it was placed inside this openlayers map div;
- Loading bar now appears on top of the time controls when they're in the bottom;
- Progress bar is now thinner;
- Fixed a problem where errors wouldn't remove the loading bar and it would load forever.
> Added back proper loading bar with fixes

- src/components/Time/ErrorManager.vue
- src/main.js
- Override to console.error to remove DomException log from OpenLayers;
- Added second check to Zoom/Pan error handling so that it wouldn't check for errors before the error was triggered.
> Fixed DomException spam and Zoom/Pan updates

- package-lock.json
- package.json
- src/mixins/datetimeManipulations.js
- Changed how guesses work for layers where times are only comma separated and the interval isn't specified;
- Upgraded luxon js library.
> Fixed guesses to be a lot more accurate and upgraded Luxon

- src/components/Map/LoadingBar.vue
- src/components/Map/MapCanvas.vue
- src/components/Map/OLControls.vue
- src/components/Time/AnimationControls/PlayPauseControls.vue
- src/views/Home.vue
- Implemented loading bar from scratch because Vuetify's loading bar always causes memory leaks;
- Made a changed for the cancelExpired flag to try and fix AniMet pannels freezing all the time.
> Re-fixed memory leak and micro-fix attempt for error handling

- src/components/Layers/LayerConfiguration.vue
- src/components/Map/SidePanel.vue
- Changed layer configurations CSS to be able to display it during an animation loop while taking less space.
> Changes for layers to be displayed during animation loop

- src/components/Animation/AnimationConfiguration.vue
- src/components/Animation/CreateAnimation.vue
- src/components/Time/LocaleSelector.vue
- src/locales/en/common.json
- src/locales/fr/common.json
- src/store/modules/Layers.js
- Dropdown inside the animation tab to switch between Image and Video output formats;
- Made sure animation and date title were properly updated depending on the format and properly kept if animation/image creation was canceled;
- Made sure button description changed and the format changed;
- Made sure refresh during image and animation worked properly;
- Fixed bug where reverting to original time zone was not saved in local storage.
> Added dropdown to select image/video output

- src/components/Time/ErrorManager.vue
- Fixed infinite error loop when non-temporal layer would fail;
- Fixed bug that would prevent animation from restarting after pausing during an error;
- Removed duplicate line of code;
- Put the entire update method in the try catch since it seems an error would sometimes occur with model runs.
> Bugfixes for 2.2.1

- .gitignore
- package-lock.json
- package.json
- Removed two useless dependencies;
- Added back generate-tree-venv in gitignore;
- Changed back name and version of AniMet in package.json;
- Added back `deploy` keyword in package.json.
> Removed useless dependencies and added back some configs

- Dockerfile
- deploy/nightly-docker/deploy-nightly.sh
- src/assets/wms_sources_configs.json
- src/stores/store.js
- Import fixed to the one that's generated in assets for wms sources;
- Changed Gebco WMS url to their new one;
- Removed vue cli install in Dockerfile.
> Fixed wms sources safeguard import, gebco wms url and removed vue cli reference

- src/components/GlobalConfigs/MapCustomizations/CustomizationMenu.vue
- src/components/GlobalConfigs/Share/PermaLink.vue
- src/components/Layers/StyleHandler.vue
- src/components/Map/GetFeatureInfo.vue
- src/components/Map/SidePanel.vue
- src/components/Time/AnimationControls/ControllerOptions.vue
- src/components/Time/LocaleSelector.vue
- src/plugins/vuetify.js
- "dark" on undefined on first login should no longer happen;
- "setPosition" error due to GFI trying to close when it didn't exist should no longer happen;
- Side panel in some cases can be toggled on/off using spacebar or other such methods, which bypassed the 250ms delay for the animation and could desync the panel from the button. Locking mechanism has been added to prevent that.
> Fixed dark, setPosition and side panel errors

- src/components/Map/GetFeatureInfo.vue
- GFI no longer tries to reposition the map on property changes;
- GFI now triggers on less duplicate events;
- GFI now doesn't trigger and closes immediately when clicking on a spot with no data while another one with data was open;
- GFI now contains coordinates:
- Coordinates representation will change between 4 representations on click in a loop:
- Decimal Degrees (lat lon with + and - signs);
- Degrees and decimal minutes (degrees and minutes with N, S, E, W);
- Degrees, Minutes, Seconds (degrees, minutes and seconds with N, S, E, W);
- (default) Signed degrees (degrees with N, S, E, W).
- Representation preference will be remembered in the localstorage;
- On language change the W gets translated to O.
> Fixed GFI bugs and added coordinates with 4 representations

- package-lock.json
- package.json
- src/components/Layers/LayerTree.vue
- src/components/Map/GetFeatureInfo.vue
- src/plugins/vuetify.js
- Added lodash library to use debouncing so layer tree doesn't trigger multiple searches in a row when typing multiple characters;
- Made it so the code didn't look at every single child when searching with only 2 characters;
- Changed GFI css so the coordinates are a bit smaller, centered and underlined with appropriate css so the underlining follows the width of the current coordinates text width.
> Added debouncing for layer tree search and styling changes for GFI coordinates

- package-lock.json
A memory leak seems to be fixed inside the layer tree when upgrading both versions to latest.
> Upgraded Vuetify and Vue versions to latest

- src/components/Map/MapCanvas.vue
- src/components/Map/VectorShapes.js
- src/locales/en/common.json
- src/locales/fr/common.json
- Moved everything inside its own .js file;
- Added possibility to draw Rectangle polygon and circles as well.
> Finishing ticket 412 for shapes

- src/components/Map/MapCanvas.vue
- src/components/Map/VectorShapes.js
- src/locales/en/common.json
- src/locales/fr/common.json
- Rectangle now stays in the same form factor and instead scales and rotates on modify;
- Added Polygon draw shape.
> Modified rectangle and added polygon

- src/components/Map/VectorShapes.js
- Hover was finicky with multiple features, added map.on click event to make sure clicking inside a feature will reselect it if it wasn't;
- Removed opacity inside features;
- Removed duplicate code and put redundant code inside addGeometry.
> Fixed click to reselect geometry and removed duplicate code

- src/assets/presets/tree_en_presets.js
- src/assets/presets/tree_fr_presets.js
- src/components/Composables/TreeNode.vue
- Presets menus are now all open by default;
- Layers are now added with the proper order from the presets;
- Preset titles in english have been capitalized (i.e. Radar rain -> Radar Rain);
- When all layers of a preset are currently added, the preset will show a blue border and will slightly increase in scale, also works from permalinks.
> Presets open by default, eng capitalization, selected preset border

- scripts/wms_sources_configs.py
- src/components/Layers/OpacityHandler.vue
- Presets on nightly now using nightly URL;
- Opacity now back to updating properly inside the permalink.
> Fixed nightly source and opacity in permalink

- src/components/Animation/AnimationCanvas.vue
- src/components/GlobalConfigs/MapCustomizations/MapPreviews.vue
- Added projection and tilegrid in animation for overlays;
- Clipped extent for 3978 and 3995 for placenames and boundaries.
> Fixed animation with overlays in 3995 and 3978 and extent clipping

- src/components/GlobalConfigs/MapCustomizations/MapPreviews.vue
- Added scaleranks for 9 and 10.
> Added all scalerank levels

- scripts/wms_sources_configs.py
- src/components/Layers/LayerTree.vue
- Fixed a small bug where validation flag wasn't used because Presets was selected as the source;
- Made Weather and Climate always display.
> Small fix for similar sources and made GeoMet Weather and Climate ops always display

- src/components/GlobalConfigs/MapCustomizations/CustomizationMenu.vue
- src/components/GlobalConfigs/MapCustomizations/MapPreviews.vue
- src/components/GlobalConfigs/PageTheme.vue
- src/components/GlobalConfigs/Share/PermaLink.vue
- src/components/Layers/LayerTree.vue
- src/components/Layers/StyleHandler.vue
- src/components/Map/GetFeatureInfo.vue
- src/components/Time/AnimationControls/ControllerOptions.vue
- src/components/Time/LocaleSelector.vue
- Added additionnal check for value of "dark";
- Made sure if no basemap was set as default it should set 'OSM'.
> 2.3 bugfixes for page load

- src/components/Composables/isDarkTheme.js
- src/components/GlobalConfigs/MapCustomizations/CustomizationMenu.vue
- src/components/GlobalConfigs/PageTheme.vue
- src/components/GlobalConfigs/Share/PermaLink.vue
- src/components/Layers/LayerTree.vue
- src/components/Layers/StyleHandler.vue
- src/components/Map/GetFeatureInfo.vue
- src/components/Time/AnimationControls/ControllerOptions.vue
- src/components/Time/LocaleSelector.vue
- Removed all computed "isDark"'s and put it as a single computed value in a composable file instead.
> isDark now only computed at a single spot

- src/locales/en/common.json
- src/locales/fr/common.json
Animate -> Export for the MP4/Image creation panel.
> Changed animate tab to export tab
