src/locales/en/common.json
src/locales/fr/common.json
src/store/modules/Layers.js

Added water bodies overlay.
Since toporama was only http and not https, it needed to be changed. As such, even though they are very light and sometimes not very helpful,  canvec layers will now be used for all of the current overlays.

Added water bodies and removed toporama for canvec

---

src/components/MapViewer.vue

Permalink now properly updates when you create one with a certain color, then undo and try to create a new one.

Fixed permalink color bug

---

src/components/Animation/CreateAnimation.vue
src/components/Animation/ExportAnimation.vue
src/components/Layers/ModelRunHandler.vue
src/components/Map/MapCanvas.vue
src/components/Share/PermaLink.vue
src/components/Time/ExpiredTimestepManager.vue
src/components/Time/TimeControls.vue
src/components/Time/TimeSlider.vue
src/mixins/datetimeManipulations.js
src/store/modules/Layers.js

Fixed:
- Date format inside animation filename;
- Monthly and Yearly now work for GeoMet-Weather as well;
- Visibility of the layer from the permalink is now correct;
- Adding a new layer from a different timestep will be correctly set invisible if the current map time is out of bounds;
- Snapped layer logic reduced when adding a new time layer;
- Layers with start time the same as end time (like PT0H) now work properly;
- animation won't fail if you cleared title prior;
- Date now changed to snappedLayer default time when map time changes;
- Fixed legend not being applied when coming from permalink.
Added:
- Scale line on the map.

Bugfixes for 1.2 release

---

src/components/Layers/LayerTree.vue
src/components/Time/ExpiredTimestepManager.vue

This MR ensure that the `LANG` query parameter is not passed when querying the GetCapabilities document for temporal dimensions. This ensures that GetCapabilities and GetMap requests made via AniMet are always made to the same mapfile.
CC @PhilippeTh @kngai

remove use of lang query param when fetching dimensions from GetCapa

---

scripts/generate_trees_layers_list.py
src/assets/trees/index.js
src/components/Layers/LayerTree.vue
src/components/Layers/StyleHandler.vue
src/components/Map/LegendControls.vue
src/components/Map/LegendSelector.vue
src/components/Map/MapCanvas.vue
src/components/Time/ExpiredTimestepManager.vue
src/locales/en/common.json
src/locales/fr/common.json
src/store/modules/Layers.js

- Generation script now deletes trees en/fr and layers en/fr files before creating new ones so that you don't keep old configs even when you change them;
- Imports are now automated inside Layers.js so that you need only run the generate script and the imports will be done automatically;
- Added index.js file that exports all trees so that they can then be imported in a batch by Layers.js;
- Added an error case where the WMS cannot be querried with the legend name but is still queriable;
- Added an error case where a layer could be in the layerTree's added list but not inside the layers list;
- Added a case where the URL for the config needed to include special parameters like `https://eccharts.ecmwf.int/wms/?token=public` that won't work if `?token=public` is not present (now you can …

Added possibility to add custom WMS sources more easily

---

src/components/Layers/StyleHandler.vue
src/components/Map/MapCanvas.vue
src/components/Time/ExpiredTimestepManager.vue
src/mixins/datetimeManipulations.js

- Realized that the bug of STYLES not being able to be put inside the getMap URL was actually because other sources seems to use STYLE without the `S`, so changed that;
- PT0H layers now properly snap when changing model runs.

Fixed STYLE and PT0H snapping

---

src/components/Layers/LayerConfiguration.vue
src/components/Layers/LayerTree.vue
src/components/Layers/StyleHandler.vue
src/components/Map/MapCanvas.vue
src/components/Time/ExpiredTimestepManager.vue
src/store/modules/Layers.js

- Fixed hardcoded path in Layers.js so that won't trip the configs;
- Fixed css so the the icons don't disappear when screen is shrunk;
- Changed parameter names to match WMS specifications.

Fixed hardcoded path in Layers.js and icons overlapped when layer names are too long

---

src/components/Animation/CreateAnimation.vue
src/components/Map/LegendControls.vue
src/components/Map/LegendSelector.vue
src/components/Map/MapCanvas.vue
src/components/Time/PlayPauseControls.vue
src/locales/en/common.json
src/locales/fr/common.json
src/store/modules/Layers.js
src/views/Home.vue

Legend differentiation:
- Added switch inside legend menu to toggle color border;
- Color border is now applied with a random color to each legend when a layer is added. Will only be displayed is the switch is on;
- Checkbox for the layer legend selection will be the same color as the legend's border;
- Border also appears in animation and a bullet of the same color will appear on the left of the layer's name in the layer list;
- Used HSV to stay within the same color range and not give colors like flashy green that would be annoying to look at;
- Changed "nudge-bottom" to 0 to move the legend selector completely over the button rather than overlapping the button a bit.
Replay button:
- Added a lock for the PlayPause function to prevent spamming and sending multiple play events at once …

Added legend differentiation and replay button

---

src/components/Animation/CreateAnimation.vue
src/components/Time/ExpiredTimestepManager.vue

- Animation background now fully white instead of black when making it invisible;
- Added small error case for when and entire layer's timesteps are missing.

Fixed animation with white background and corrected error case

---

src/components/HeaderFooter/AppBar.vue

If you never set a preference for AniMet, it will set light/dark according to your preference in your browser.
If you did change it manually, it will remember that choice for future visits.

Light/dark mode is now remembered by AniMet

---

src/components/Time/TimeControls.vue

dateFormat -> layerDateFormat, currently on nightly climate is no longer working because of that

Fixed variable missnaming that caused all time formmats to be ISO

---

src/components/Animation/AnimationRectangle.vue
src/components/Animation/CreateAnimation.vue
src/components/Time/TimeControls.vue

- Fixed time controls collapse invisible between 1051 and 1120px
- Fixed error in the terminal when animation rectangle would try to create the preview when no time layers were there
- Removed seconds from the output animation time

Last minute fixes

---

src/components/Time/TimeSlider.vue

Small change to make the orange play-head take priority over either of the range slider's thumbs

Play-Head now takes priority over extent slider

---

src/components/Time/AnimationControls/PlayPauseControls.vue

Linking the switch from the time controls and animation caused issues and is not necessarily desired behavior either.
Created a separate variable for the time controller instead.

Unlinked animation and playback reversed controls

---

src/components/Animation/CreateAnimation.vue
src/components/Map/MapCanvas.vue
src/components/Time/ErrorManager.vue
vue.config.js

- Fixed a bug where a method wasn't referenced with `this.`
- Fixed a bug where layer would crash on firefox on missing timestep rather than removing the timestep
- Fixed a bug where animation events would duplicate on missing timestep rather than end and restart (old event never stopped so the method was trying to start from the beginning and from where it crashed at the same time)
- Fixed a bug where "initialState" would be further than the last timestep of the extent because missing timesteps were removed
- Added special config to see files appear on chrome again

Multiple bugfixes and config change for chrome

---

src/components/GlobalConfigs/LegendSelector.vue
src/components/GlobalConfigs/Share/PermaLink.vue
src/components/Map/MapCanvas.vue
src/views/Home.vue

The legend added to the map when loading from a permalink has always been the fastest layer to load. As such there was no consistency for the legend when loading from the permalink. Made a change so that it would be remembered for each layer and so that old permalinks would still work no problem.

Which layer legends are active is now remembered as part of the permalink

---

src/components/Map/GetFeatureInfo.vue

Fixed a bug where I would try to translate the "value" GFI property of a layer that did not have a "value" property.

Fixed error when language changed while GFI open

---

src/components/GlobalConfigs/Share/PermaLink.vue
src/components/Map/CustomOLControls.vue
src/components/Map/GlobalConfigs.vue
src/components/Map/SidePanel.vue
src/components/Time/TimeControls.vue
src/router/index.js
src/store/modules/Layers.js
src/views/Home.vue

Add `&hide=` with the appropriate parameters in the permalink to hide those components from the screen.
Used so AniMet can be put as a small iframe inside a website without having all the clutter surrounding it.
Parameters are:
- `title` to hide the title;
- `top` to hide the top icons;
- `time` to remove the time controls;
- `side` to remove the side panel;
- `zoom` to remove the zoom buttons;
- `all` to remove all of the above.

Added hide router property to hide different parts of the UI

---

src/components/GlobalConfigs/Share/PermaLink.vue
src/components/Map/CustomOLControls.vue
src/components/Map/GlobalConfigs.vue
src/components/Map/LegendControls.vue
src/components/Map/MapCanvas.vue
src/components/Map/SidePanel.vue
src/components/Time/TimeControls.vue
src/router/index.js
src/store/modules/Layers.js
src/views/Home.vue

Ability to hide was initially added to use as part of a thumbnail, but it would load quite slowly and the components were just hidden, but the code still had to wait for them to be rendered before hiding them, which made it even worse.
As such, hide parameter has been removed from the permalink and all the code associated with it.
(Did not want to revert merge since I also pushed bugfixes with it)

Removed hide since poor implementation and not used

---

src/components/Map/GetFeatureInfo.vue

GFI urls and words in tooltips no longer break out of the container if they're too long.

Prevent GFI tooltip from breaking out

---

src/components/GlobalConfigs/LegendSelector.vue
src/components/Layers/StyleHandler.vue

Fixed small bug where the legends' order was the opposite of the layer configuration.
Fixed a bug where the legends in the style selector would be too wide and put the menu outside the screen.

Fixed legends ordering and wrong menu size

---

src/components/Animation/AnimationConfiguration.vue
src/components/Animation/CreateAnimation.vue
src/components/Layers/LayerConfiguration.vue
src/components/Map/LegendControls.vue
src/components/Map/MapCanvas.vue
src/mixins/IntegerAssigner.js
src/store/modules/Layers.js

- Legends will now always be added to the map by default, not just the first layer added;
- Legend will now be hidden when the layer is hidden;
- Removed unused screen dimensions checks in some files;
- Legends will now be added with a slight offset from one another;
- New class IntegerAssigner.js added to assign integers and determine legends positions with them;
- Loading variable for the map changed so the loading is staying until everything is done loading.

Legends now automatically added and hidden when layer is hidden

---

src/components/Time/TimeControls.vue
src/components/Time/TimeSlider.vue

Instead of just having a chevron-up icon when time controls is lowered, show the current map time.

Show current time when time controls are collapsed

---

src/components/Animation/AnimationCanvas.vue
src/components/Animation/AnimationConfiguration.vue
src/components/Layers/ModelRunHandler.vue
src/components/Map/MapCanvas.vue
src/components/Time/AutoRefresh.vue
src/components/Time/ErrorManager.vue
src/components/Time/TimeControls.vue
src/locales/en/common.json
src/locales/fr/common.json

- Model run handling fixed:
- If selected model run is the last one, update as new ones come in;
- If another model run is manually selected, keep it for as long as possible;
- Once a model run is no longer available, reset back to latest and start updating with new MRs again.
- Small improvements to `AnimationCanvas` layers' loading/loaded tracker;
- Disabled color border switch during animation;
- `AutoRefresh` file added. Keeps track of time-enabled layers and checks every 1min30sec to see if any of them have had updates to their getCapas;
- Permalink is now updated when a legend is removed through the `del` keyboard key;
- `AutoRefresh` uses `ErrorManager`'s `RefreshExpired` since it's the same thing;
- `blockRefresh` flag has been added to make sure errors and refreshes don't fight …

Auto refresh finally working

---

src/components/Map/LegendControls.vue

When a layer is put invisible, legend is put to `Display: none`, but not removed, so just need to make sure to remove the intersect in that case.

Remove intersect message on legend hidden

---

src/components/Map/CustomOLControls.vue
src/components/Map/MapCanvas.vue
src/components/Time/AutoRefresh.vue
src/components/Time/TimeControls.vue
src/router/index.js
src/views/FourDisplays.vue

- Added a manual refresh on all non time-enabled layers every 9min;
- Changed the date in collapsed controls to be on 2 lines and the time is a bit bigger;
- Added a simple FourDisplays view that just contains 4 animets for big TV displays (semi-official feature).

Refresh on non-time enabled, date size increase and 4-displays

---

deploy/gh-pages/deploy.sh
src/views/FourDisplays.vue

When you’d be going on a wrong route, the page is gonna go “404 not found”, so by putting the entire index.html as 404.html, instead of throwing 404 it’ll go “ah ok I need to use your router for this 404” and it’ll go to my 404 or my other route accordingly.

Added 404.html so github.io uses vue router

---

src/views/FourDisplays.vue

On page refresh or page close, store the permalink for each iframe inside localStorage and load localStorage urls if they exist.

4-Displays page will not remember each panel's permalink

---

src/components/Map/LegendControls.vue

Fixed a bug where the warning message would not appear on intersection between legend and animation rectangle when the layer was out of bounds (red eye icon).

Fixed warning message not appearing on OOB

---

src/components/Animation/AnimationCanvas.vue
src/components/Layers/LayerTree.vue
src/components/Map/MapCanvas.vue
src/components/Time/AnimationControls/PlayPauseControls.vue
src/components/Time/ErrorManager.vue

- Changed how the play loop worked slightly to try and make it so the `fixTimeExtent` method gets called whenever there's an issue, which should fix Freezes and timesteps erroring out and not being removed from the extent;
- Added possibility to remove or add layers during a `Play` event. It will stop the animation and do the desired action;
- Pressing the `Pause` button will no longer change tabs to layer configs, only pressing `Play` does now.

Fix attempt for network errors causing freezes and add/remove layers during animation

---

src/components/Animation/AnimationRectangle.vue
src/components/Map/LegendControls.vue
src/components/Map/SidePanel.vue

- Change `display: none` to `visibility:hidden` so that the animation preview's size doesn't go to 0x0 when it disappears. Otherwise this would make legends disappear from the animation output whenever you changed the tab while it was being made.

Fixed legends disappearing when changing tabs during animation creation

---

src/components/Layers/StyleHandler.vue
src/components/Map/LegendControls.vue
src/components/Time/TimeControls.vue

- Adding the first time-enabled layer will now no longer Snap by default;
- Legends now change depending on the current language. Styles menu changed to reflect this change as well, although this makes it so every single available legend is queried every time the language is changed to update the styles menu.

Fixed legends lang and snapped no longer default

---

src/components/Animation/AnimationConfiguration.vue
src/components/Layers/LayerConfiguration.vue
src/components/Layers/LayerTree.vue
src/components/Map/GlobalConfigs.vue
src/components/Map/LegendControls.vue
src/components/Map/MapCanvas.vue
src/components/Map/OLControls.vue
src/components/Map/SidePanel.vue
src/components/Time/TimeControls.vue

- Global icons on the top right now wait for md screen size (960px) instead of lg (1264px) before moving under the AniMet logo;
- Fixed some slight adjustments issues with menu sizes during resize;
- Made it so the collapsed time controls stay small for as long as possible;
- Adjusted screen elements to match collapsed controls new positioning;
- Collapsed time controls now display the time in the correct format when timestep is monthly or yearly.

Fixed formatting issues with dates and screen sizes

---

package-lock.json
package.json
src/components/Animation/AnimationConfiguration.vue
src/components/Animation/CreateAnimation.vue
src/components/Layers/LayerTree.vue
src/components/Time/AutoRefresh.vue
src/components/Time/ErrorManager.vue
src/components/Time/TimeControls.vue
src/locales/en/common.json
src/locales/fr/common.json
src/utils/AxiosConfig.js

- Added axios-retry library to make axios retry 4 times taking longer and longer between retries to try and reduce odds of failure on timeouts and such (which in a loop is handled but takes 45sec to retry so this should still be better). Hard to test though so will need to see if it introduces any kind of errors;
- Animate in reverse switch, fps selector and output format selector disabled when start === end (single frame animation turns into image) and reverse switch, fps selector disabled also when output format is not MP4;
- Create animation/image button now disabled when all the layers are set invisible and tooltip appears over it only when disabled (previously would do nothing without telling the user why);
- It seems `updateSize()` no longer triggered the `rendercomplete` event, so …

Multiple bugfixes and small improvements

---

src/components/Animation/AnimationCanvas.vue
src/components/Animation/CreateAnimation.vue
src/components/Time/AnimationControls/PlayPauseControls.vue
src/components/Time/ErrorManager.vue
src/locales/en/common.json
src/locales/fr/common.json
src/store/modules/Layers.js

- Fixed panels freezing during a loop if the connection is particularly unstable;
- Fixed animation creation crashing during error handling;
- Fixed layers getting removed from AniMet during idle or animation creation during connection errors;
- Removed no longer used `cancelExpired` flag from animation canvas;
- Error list properly resets however many times a layer triggers an error;
- Changed error retry to every 20 sec instead of 45;
- Auto-refresh disabled during animation creation;
- Fixed time continuing to move forward during critical error because critical error flag wasn't triggered fast enough;
- Added error handling if error happens during the refresh query and not in the initial query.

Bugfixes for 2.2.1

---

src/components/Time/ErrorManager.vue

Split `blockRefresh` variable into two different variables. If an error appears during an animation, the flag would be put to block the refresh during the error, then when the error was handled the block was set to false since the error was handled, which is desired behavior except during the animation creation. Thus the flags were split to make sure they don't sabotage one another.

2 different blocks so that an error doesn't re-enable animation refresh

---

src/components/Layers/LayerTree.vue

If you tried to add a layer and said layer failed on initial load, subsequent clicks on the `+` icon to add the layer wouldn't do anything. Added the layer ID to the list of added layers after the initial request has successfully been made to remedy that problem. Also removed an unused variable.

Fixed layer could no longer be added on loading failure

---

src/components/Time/AnimationControls/ControllerOptions.vue
src/components/Time/AnimationControls/PlayPauseControls.vue
src/components/Time/TimeControls.vue
src/components/Time/TimeSlider.vue

- Play/Pause/Replay buttons now appear on the collapsed controls;
- When collapsed, icon changes to be simpler and a bit smaller to take less real estate;
- Fixed bug where unmounting component and remounting it while Playing the loop would cause the unmounted component to never stop and every time this would happen the loop would skip 1 more timestep (unnoticeable before since for this to happen you needed to press play and then reduce your screen to phone size).

Added Play Pause to the collapsed controls and fixed component remounting bug

---

scripts/generate_trees_layers_list.py
src/store/modules/Layers.js

This PR ensures that if errors are encountered when reading the GetCapabilities documents of services defined in the `scripts/wms_sources_configs.json` file, they are simply ignored instead of causing the layer tree generation to fail. The problematic source is removed from the sources list and a "cleaned" WMS sources JSON document is now added to the `src/assets` directory to be used by the `src/store/modules/Layer.js` module.

Safeguard wms source errors

---

public/index.html
src/components/Animation/CreateAnimation.vue

This PR removes Matomo tracking and events following the shutdown of the msc-analytics Matomo instance.

remove matomo analytics and events

---

src/components/Animation/AnimationConfiguration.vue
src/components/GlobalConfigs/Share/PermaLink.vue
src/components/Layers/LayerTree.vue
src/components/Map/MapCanvas.vue
src/components/Time/ErrorManager.vue
src/components/Time/LocaleSelector.vue
src/components/Time/TimeControls.vue
src/components/Time/TimeSlider.vue

- Layer tree no longer breaks when trying to query a layer that in unavailable and a snackbar will appear to let you know there's a problem;
- Fixed an edge case where if a layer was remove during handling of an error a loadingError would be sent with a layer with a value of undefined;
- Fixed an edge case where errors would loop indefinitely when a layer is removed during error handling;
- Layer will now be removed from AniMet when the error `Unable to access file` while not in a loop or animating instead of showing service unavailable;
- Fixed an edge case where the map time would try to update even though there were no time layers left;
- Fixed styling of the range slider when thumbs are overlapping (only noticeable when disabled like for single timestep layers like caldas);
- Fixed …

Fixed some time edge cases, layer tree failure and range slider styling

---

src/components/GlobalConfigs/MapCustomizations/CustomizationMenu.vue
src/components/Layers/LayerTree.vue
src/components/Map/SidePanel.vue
src/components/Time/ErrorManager.vue
src/locales/en/common.json
src/locales/fr/common.json
src/views/Home.vue

- Removed some unused CSS classes;
- Added proper handling for attempts of adding layers on a unsupported CRS;
- Fixed tabs automatically changing to configurations tab seemingly randomly and sometimes staying on configurations tab even though the layers list was empty.

Fixed invalid CRS handling and finicky auto tab switch

---

scripts/generate_trees_layers_list.py
scripts/wms_sources_configs.py
src/components/Layers/LayerTree.vue
src/locales/en/common.json
src/locales/fr/common.json

Small changes to allow NRCan as a WMS source on Nightly.
Fixed small bug where $refs reset wasn't resetting anything when more than 2 trees existed.

Added NRCan as a source for Nightly since the overlays tab was removed

---

src/components/Animation/AnimationCanvas.vue
src/components/Map/EditableTextBox.vue
src/components/Map/LegendControls.vue
src/components/Map/MapCanvas.vue
src/locales/en/common.json
src/locales/fr/common.json

- Added Vector arrows than can be translated and rotated;
- Arrows also appear in the animation;
- Fixed textbox so it would work in Firefox;
- Textboxes can now be deleted on tablets;
- Legends now have an X button on the top right on hover OR always visible for touch screens;
- Legends now don't "remember" the last legend that was clicked and if you click away from a legend it will no longer be selected (so that pressing delete after clicking elsewhere won't affect the last clicked legend);
- Context menu now translates on language change;
- Vector arrows can be deleted when selected and clicking the delete key OR on touch devices selecting the arrow and then holding on it for 1.5sec will slowly reduce opacity until it is removed entirely;
- GFI will not open if you click on a vector …

Fixed textbox and added vector arrow

---

scripts/wms_sources_configs.py
src/mixins/datetimeManipulations.js

- Needed to add a regex case to merge the first date and interval in the ECMWF WMS, i.e.:
`2025-01-29T12:00:00Z,2025-01-29T15:00:00Z/2025-02-09T00:00:00Z/PT3H`
needed to become
`2025-01-29T12:00:00Z/2025-02-09T00:00:00Z/PT3H`

ECMWF added as a nightly source

---

src/components/Map/GetFeatureInfo.vue

Since we pop the "value" property out of "properties" in the GFI, there was a bug for climate where you'd see a dropdown for properties that would disappear as soon as you clicked on it because it no longer contained anything. Just added a small check to not add properties in case it's empty.

Fixed GFI having empty properties when it only contained Value prop

---

src/components/Layers/LayerTree.vue

Fixed layer tree Node adding the source tag in the layer tree, making it unaware of layers added from specific sources after coming from a permalink:

Fixed Node changing its name with the source in the layer tree

---

src/components/Map/LegendControls.vue

Maximum legend width on load of 25% on cellphone, 35% on any other screen size.

Added maximum legend width on image load(mostly for cellphone)

---

src/components/GlobalConfigs/PageTheme.vue

AniMet before used localStorage values for light/dark theme of `true/false`
Now it’s `light/dark`
But my check was looking at “if there’s no value for theme, set it, otherwise take the one that’s there”, which was setting the theme to, for example, `true` instead of `light`.
This is also why the bug stopped appearing as soon as you clicked on the theme button a single time and whatever you did you couldn't reproduce afterwards, it's because it was an artifact from the previous version's local storage which, after clicking once, no longer exists.

Actually found the dark bug

---

src/components/Animation/AnimationConfiguration.vue
src/components/Composables/TreeNode.vue
src/components/Layers/LayerConfiguration.vue
src/components/Layers/LayerTree.vue
src/components/Map/SidePanel.vue
src/utils/AxiosConfig.js

- Added dvh for phone displays instead of vh;
- Made presets appear on 3 columns instead of 4 for smaller displays;
- Auth retry and should now always ask for authentication when required;
- Try/Catch for the axios create instance so layer add can be retried.

Fixed phone UI problems and auth retry

---

src/assets/presets/presets.js
src/components/Layers/LayerConfiguration.vue
src/components/Time/AnimationControls/PlayPauseControls.vue

- Extrapolation layers added to radar Snow and radar Rain presets;
- Layers that are not showed because they are out of bounds will also be greyed out in the config panel;
- Reduced minimum time between time jumps from 1 sec to 250ms when playing.

Added extrapolation to presets, reduced play delay to 250ms, text disabled when layer is OOB

---

src/assets/presets/presets.js
src/components/GlobalConfigs/Share/PermaLink.vue
src/components/Layers/LayerTree.vue
src/components/Map/MapCanvas.vue
src/components/Time/AnimationControls/PlayPauseControls.vue
src/components/Time/TimeControls.vue
src/router/index.js
src/views/Home.vue

- Added new parameter in the permalink "range" that remembers indices of the time controls and the selected time interval `&range=first,current,last,step`;
- Changed opacity of radar presets layers to 0.9;
- Fixed bug where coming from a permalink with `play=1` could sometimes cause the timesteps to move forward without waiting for the layers to be done loading.

Added first/current/last/step range param in permalink

---

src/components/Map/GetFeatureInfo.vue

A `/` separator is present when a WMS source is tagged as being a duplicate of another to differentiate layers with the same name. Moved that source part to its own property inside the GFI as `Source` under the value instead of seeing it in the layer name.

Moved GFI source name to its own property

---

src/components/Layers/LayerTree.vue
src/components/Map/LegendControls.vue

- Legend size automatically decreased based on height compared to screen size as well, no longer just width;
- Side panel now has a bigger minimum size for vertically small displays.

Small formatting fixes for smaller displays/4-displays

---

src/components/GlobalConfigs/LanguageSelect.vue
src/components/GlobalConfigs/PageTheme.vue

Broadcast channels added so an iframe can send messages to toggle language and theme.
- AniMet first sends a request in the channel so the parent app can answer immediately what theme and language it is currently expecting;
- AniMet then keeps an event listener for changes inside the parent app itself (the parent needs to send the update by itself whenever it changes it).
Example snippet to use inside parent container to receive AniMet request:
```
this.channel.addEventListener('message', (event) => {
if (event.data.type === 'get-theme') {
this.channel.postMessage({
type: 'theme-change',
theme: this.currentTheme
})
}
})
```
Otherwise simply use the `postMessage` command whenever you need to change it:
```
this.channel.postMessage({
type: 'theme-change',
theme: this.currentTheme
})
``` …

Added boradcast channels to change theme and language from an iframe

---

src/components/Composables/TreeNode.vue
src/components/Map/MapCanvas.vue
src/stores/store.js

- The `multiAddLock` wasn't working properly with the presets, it was only stopping the same preset from being spam clicked, not different presets one after the other;
- Fixed url -> urls in the error handler after the multi-source changes for the Others section.

Fixed lock so it works through multiple instances
